export const projects = [
  {
    id: 1,
    title: ".NET Web API",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: [".NET", "Azure SQL DB"],
    github: "",
    projectlink: "",
  },
  {
    id: 2,
    title: "NodeJS Web API",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["MongoDB", "NodeJS"],
    github: "",
    projectlink: "",
  },
  {
    id: 3,
    title: "SQL Database",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["MSSQL", "SQL"],
    github: "",
    projectlink: "",
  },
  {
    id: 4,
    title: "Recommender System",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["Python"],
    github: "",
    projectlink: "",
  },
  {
    id: 5,
    title: "Online Shopper Analysis",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["R"],
    github: "",
    projectlink: "",
  },
  {
    id: 6,
    title: "Ad Campaign Analysis",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["R"],
    github: "",
    projectlink: "",
  },
  {
    id: 7,
    title: "Web Scraper",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["Python"],
    github: "",
    projectlink: "",
  },
  {
    id: 8,
    title: "OCR Converter",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ut incidunt blanditiis totam ipsam expedita quae porro temporibus dolores optio.",
    techstack: ["Python"],
    github: "",
    projectlink: "",
  },
];
